// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

#include "SmartDashboard/SmartDashboard.h"
#include "Commands/ShootCatapult.h"
#include "Commands/TankDrive.h"
#include "Commands/WheelShooter.h"

OI::OI() {
    // Process operator interface input here.
    rightJoystick.reset(new Joystick(0));
    leftJoystick.reset(new Joystick(1));
    
    collectorForward.reset(new JoystickButton(rightJoystick.get(), 1));
    collectorForward->WhileHeld(new WheelShooter());

    collectorReverse.reset(new JoystickButton(leftJoystick.get(), 1));
    collectorReverse->WhileHeld(new ShootCatapult());
    operatorJoystick.reset(new Joystick(1));

    // SmartDashboard Buttons
    SmartDashboard::PutData("TankDrive", new TankDrive());
    printf("Initialized OI");
}

std::shared_ptr<Joystick> OI::getOperatorJoystick() {
   return operatorJoystick;
}

std::shared_ptr<Joystick> OI::getLeftJoystick() {
   return leftJoystick;
}

std::shared_ptr<Joystick> OI::getRightJoystick() {
   return rightJoystick;
}
